spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/baeminchan;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


handlebars:
  suffix: .html
  cache: false
  expose-session-attributes: true


---
spring:
  profiles: local

---
spring:
  profiles: test

---
spring:
  profiles: dev


---
spring:
  profiles: production